espnet: '202209'
files:
  asr_model_file: exp/asr_train_asr_1410_raw_all_turkic_1610_char_sp/valid.acc.ave_10best.pth
  lm_file: exp/lm_train_lm_1410_all_turkic_1610_char/valid.loss.ave_10best.pth
python: "3.9.12 (main, Apr  5 2022, 06:56:58) \n[GCC 7.5.0]"
timestamp: 1669109899.076291
torch: 1.13.0
yaml_files:
  asr_train_config: exp/asr_train_asr_1410_raw_all_turkic_1610_char_sp/config.yaml
  lm_train_config: exp/lm_train_lm_1410_all_turkic_1610_char/config.yaml
