config: conf/train_asr_1410.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/asr_train_asr_1410_raw_all_turkic_1610_char_sp
ngpu: 1
seed: 0
num_workers: 4
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: 4
dist_rank: 0
local_rank: 0
dist_master_addr: localhost
dist_master_port: 56345
dist_launcher: null
multiprocessing_distributed: true
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 60
patience: null
val_scheduler_criterion:
- valid
- acc
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
nbest_averaging_interval: 0
grad_clip: 5
grad_clip_type: 2.0
grad_noise: false
accum_grad: 4
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 20000000
valid_batch_bins: null
train_shape_file:
- exp/asr_stats_raw_all_turkic_1610_char_sp/train/speech_shape
- exp/asr_stats_raw_all_turkic_1610_char_sp/train/text_shape.char
valid_shape_file:
- exp/asr_stats_raw_all_turkic_1610_char_sp/valid/speech_shape
- exp/asr_stats_raw_all_turkic_1610_char_sp/valid/text_shape.char
batch_type: numel
valid_batch_type: null
fold_length:
- 51200
- 150
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/train_all_turkic_1610_sp/wav.scp
    - speech
    - sound
-   - dump/raw/train_all_turkic_1610_sp/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - dump/raw/dev_all_turkic_1610/wav.scp
    - speech
    - sound
-   - dump/raw/dev_all_turkic_1610/text
    - text
    - text
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.0025
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000
token_list:
- <blank>
- <unk>
- <space>
- a
- а
- i
- е
- ы
- н
- n
- e
- r
- т
- р
- l
- л
- o
- d
- k
- д
- m
- і
- s
- t
- y
- с
- м
- к
- ә
- u
- b
- б
- ı
- о
- и
- у
- h
- й
- g
- қ
- п
- ш
- ғ
- z
- ң
- ө
- г
- '[tr]'
- з
- ү
- ж
- ü
- ş
- '[ba]'
- v
- ҡ
- '[uz]'
- c
- q
- '[kk]'
- ҙ
- ى
- ç
- p
- һ
- ğ
- ұ
- ö
- я
- ا
- f
- х
- ە
- ن
- ل
- в
- ر
- э
- ت
- x
- ۇ
- ҫ
- j
- ئ
- ق
- م
- د
- ч
- ك
- ي
- ф
- ب
- س
- پ
- ю
- و
- '[tt]'
- '[ug]'
- ش
- ӑ
- ې
- ӗ
- ڭ
- غ
- ز
- ۈ
- ь
- '[ky]'
- چ
- ц
- گ
- ۆ
- ʻ
- ھ
- '[cv]'
- ۋ
- خ
- ج
- җ
- ъ
- w
- ʼ
- '[sah]'
- ҕ
- ӳ
- ҥ
- щ
- â
- ف
- ё
- ə
- ژ
- '[az]'
- õ
- û
- ӊ
- ҳ
- î
- ў
- ʙ
- ó
- ģ
- ò
- ӯ
- ë
- ј
- ƣ
- µ
- ƶ
- <sos/eos>
init: null
input_size: null
ctc_conf:
    dropout_rate: 0.0
    ctc_type: builtin
    reduce: true
    ignore_nan_grad: null
    zero_infinity: true
joint_net_conf: null
use_preprocessor: true
token_type: char
bpemodel: null
non_linguistic_symbols: data/train_all_turkic_1610/nonlyng.txt
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
short_noise_thres: 0.5
frontend: default
frontend_conf:
    fs: 16k
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
normalize: global_mvn
normalize_conf:
    stats_file: exp/asr_stats_raw_all_turkic_1610_char_sp/train/feats_stats.npz
model: espnet
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
preencoder: null
preencoder_conf: {}
encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31
postencoder: null
postencoder_conf: {}
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
required:
- output_dir
- token_list
version: '202207'
distributed: true
